version: "3.9"
services:
  app:
    container_name: voting_app
    build: ./
    volumes:
      - ./config:/go/config
      - ./controllers:/go/controllers
      - ./db:/go/db
      - ./models:/go/models
      - ./router:/go/router
      - ./services:/go/services
      - ./utils:/go/utils
      - ./main.go:/go/main.go # Changed from min.go to main.go
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - voting_network
  redis:
    container_name: redisapp
    image: "redis/redis-stack"
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data
    networks:
      - voting_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  postgres:
    container_name: postgresapp
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: voting_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - voting_network
  sqlpad:
    image: sqlpad/sqlpad:6
    depends_on:
      - postgres
    hostname: "sqlpad"
    ports:
      - "3000:3000"
    environment:
      SQLPAD_ADMIN: "admin@admin.com"
      SQLPAD_AUTH_DISABLED_DEFAULT_ROLE: "admin"
      SQLPAD_AUTH_DISABLED: "true"
      SQLPAD_APP_LOG_LEVEL: debug
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_CONNECTIONS__psql__name: psql_conn
      SQLPAD_CONNECTIONS__psql__driver: postgres
      SQLPAD_CONNECTIONS__psql__host: postgres
      SQLPAD_CONNECTIONS__psql__database: voting_app
      SQLPAD_CONNECTIONS__psql__username: user
      SQLPAD_CONNECTIONS__psql__password: password
      SQLPAD_CONNECTIONS__psql__multiStatementTransactionEnabled: "true"
      SQLPAD_CONNECTIONS__psql__idleTimeoutSeconds: 86400
    networks:
      - voting_network
volumes:
  postgres_data:
networks:
  voting_network:
